### ISSUE TITLE
403 Forbidden with team-related links on dashboard menu bar

### ISSUE THREAD

**Issue by sophialee0416** [tamuhack-org/Ouroboros#262] opened 2019-10-26 22:33 UTC
**Describe the Bug**
Clicking `Create Team` or `Join Team` Buttons *before* starting/completing application leads to a 403 Error page. I don't know if this is a WIP, intentional, or a bug.

**To Reproduce**
1. Create and verify account
2. *Before* creating an application, select the `Create Team` or `Join Team` Buttons
3. Should lead to a 403 Error Page

**Expected behavior**
Either button should be disabled until an application is created, or it should lead to another page for further clarification for the user

**Additional Details**
Encountered while going thru Issue #230

**Comment by SaltyQuetzals** [comment] 2019-10-27 20:31
Duplicate of #246

**Closed by SaltyQuetzals** 2019-10-27 20:31 UTC
Labels: bug
