### ISSUE TITLE
Design: Remove create/join team nav tabs when user hasn't applied

### ISSUE THREAD

**Issue by cameron3301** [tamuhack-org/Ouroboros#288] opened 2019-10-29 03:52 UTC
**Describe the Bug**
After a user verifies their account, they are taken to the status page and given the option to create an application. At this point, the user is not allowed to create a team or join a team BUT there are navigation tabs shown at this page for creating and joining a team. These should only be visible when the user is actually able to create / join a team.

**To Reproduce**
1. Create a new user
2. Verify the user's account
3. Go to the status page, after email verification
4. See navigation tabs

**Screenshots**
![image](https://user-images.githubusercontent.com/37715360/67736403-8074cf80-f9d5-11e9-8e37-9812df48b855.png)

**Comment by SaltyQuetzals** [comment] 2019-10-29 04:39
Duplicate of #246 and #262

**Closed by SaltyQuetzals** 2019-10-29 04:39 UTC
Labels: bug
