### ISSUE TITLE
Login page is Django admin page and not logout UI

### ISSUE THREAD

**Issue by jonathan-innis** [tamuhack-org/Ouroboros#247] opened 2019-10-23 03:39 UTC
**Describe the Bug**
Rather than the user getting a nice logout UI when they logout or being redirected to the home page, they are taken to a Django admin page that does not look good.

**To Reproduce**
1. Login as a user
2. Click the logout button on the status page

**Expected behavior**
Logout page should provide a nice UI to the user.

**Comment by SaltyQuetzals** [comment] 2019-10-23 04:51
Duplicate of #242

**Closed by SaltyQuetzals** 2019-10-23 04:51 UTC
Labels: bug
